// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcWzI8sXCgaJCuotFlUGZoDagL8iwyMq0',
    appId: '1:1064694430703:web:827fbb102ee043f56d141a',
    messagingSenderId: '1064694430703',
    projectId: 'final-enroll-app',
    authDomain: 'final-enroll-app.firebaseapp.com',
    storageBucket: 'final-enroll-app.firebasestorage.app',
    measurementId: 'G-36B30GLFNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuNfR6DRiQBi8oexOi1RRC7f8zTEz2AUw',
    appId: '1:1064694430703:android:04709cbecd672bcf6d141a',
    messagingSenderId: '1064694430703',
    projectId: 'final-enroll-app',
    storageBucket: 'final-enroll-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2o6lvzRAABRCc547_4nJQKx2H155aLKw',
    appId: '1:1064694430703:ios:6551f4113c1842dc6d141a',
    messagingSenderId: '1064694430703',
    projectId: 'final-enroll-app',
    storageBucket: 'final-enroll-app.firebasestorage.app',
    iosBundleId: 'com.example.enrollApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2o6lvzRAABRCc547_4nJQKx2H155aLKw',
    appId: '1:1064694430703:ios:6551f4113c1842dc6d141a',
    messagingSenderId: '1064694430703',
    projectId: 'final-enroll-app',
    storageBucket: 'final-enroll-app.firebasestorage.app',
    iosBundleId: 'com.example.enrollApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcWzI8sXCgaJCuotFlUGZoDagL8iwyMq0',
    appId: '1:1064694430703:web:d936b07d5e8343446d141a',
    messagingSenderId: '1064694430703',
    projectId: 'final-enroll-app',
    authDomain: 'final-enroll-app.firebaseapp.com',
    storageBucket: 'final-enroll-app.firebasestorage.app',
    measurementId: 'G-7SKGLFNQS5',
  );
}
